apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: {{ .Values.appName }}
data:
  POSTGRES_DB: {{ .Values.configMap.POSTGRES_DB }}
  POSTGRES_USER: {{ .Values.configMap.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.configMap.POSTGRES_PASSWORD }}